route:
  receiver: pager
  group_by: [alertname]
  group_wait: 2s
  group_interval: 5s
  repeat_interval: 1m

receivers:
  - name: pager
    webhook_configs:
      - url: http://app:9182/webhook
        send_resolved: true
