global:
  scrape_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  # Objetivo: descobrir alvos via http_sd no sd-server e transformar
  # __meta_datacenter e __meta_owner_team em labels datacenter e owner_team.
  - job_name: http-sd
    http_sd_configs:
      - url: http://sd-server:8000/targets
        refresh_interval: 15s
    relabel_configs:
      - action: labelmap
        regex: __meta_(.+)
