global:
  scrape_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  # Objetivo: raspar SÓ os alvos do time payments.
  - job_name: payments-only
    file_sd_configs:
      - files: [/etc/prometheus/sd/apps.json]
    relabel_configs:
      - source_labels: [team]
        regex: payment
        action: keep
